import ArrowLeftIcon from '@/components/icons/ArrowLeftIcon.vue';
import ChevronRightIcon from '@/components/icons/ChevronRightIcon.vue';
import DeviceIcon from '@/components/icons/DeviceIcon.vue';
import DotsVerticalIcon from '@/components/icons/DotsVerticalIcon.vue';
import EyeIcon from '@/components/icons/EyeIcon.vue';
import EyeOffIcon from '@/components/icons/EyeOffIcon.vue';
import HomeIcon from '@/components/icons/HomeIcon.vue';
import PieChartIcon from '@/components/icons/PieChartIcon.vue';
import PluginIcon from '@/components/icons/PluginIcon.vue';
import RepeatIcon from '@/components/icons/RepeatIcon.vue';
import ServerIcon from '@/components/icons/ServerIcon.vue';
import SettingsIcon from '@/components/icons/SettingsIcon.vue';
import UserIcon from '@/components/icons/UserIcon.vue';
import BellIcon from '@/components/icons/BellIcon.vue';
import MenuIcon from '@/components/icons/MenuIcon.vue';
import CloseIcon from '@/components/icons/CloseIcon.vue';
import InboxIcon from '@/components/icons/InboxIcon.vue';
import ChevronDoubleRightIcon from '@/components/icons/ChevronDoubleRightIcon.vue';
import ChevronDoubleLeftIcon from '@/components/icons/ChevronDoubleLeftIcon.vue';
import LogoutIcon from '@/components/icons/LogoutIcon.vue';
import PowerIcon from '@/components/icons/PowerIcon.vue';
import BulbIcon from '@/components/icons/BulbIcon.vue';
import EditIcon from '@/components/icons/EditIcon.vue';
import FolderIcon from '@/components/icons/FolderIcon.vue';
import UsersIcon from '@/components/icons/UsersIcon.vue';
import { App } from '@vue/runtime-core';

export default {
  install(app: App) {
    app.component('ArrowLeftIcon', ArrowLeftIcon);
    app.component('ChevronRightIcon', ChevronRightIcon);
    app.component('DeviceIcon', DeviceIcon);
    app.component('DotsVerticalIcon', DotsVerticalIcon);
    app.component('EyeIcon', EyeIcon);
    app.component('EyeOffIcon', EyeOffIcon);
    app.component('HomeIcon', HomeIcon);
    app.component('PieChartIcon', PieChartIcon);
    app.component('PluginIcon', PluginIcon);
    app.component('RepeatIcon', RepeatIcon);
    app.component('ServerIcon', ServerIcon);
    app.component('SettingsIcon', SettingsIcon);
    app.component('UserIcon', UserIcon);
    app.component('BellIcon', BellIcon);
    app.component('MenuIcon', MenuIcon);
    app.component('CloseIcon', CloseIcon);
    app.component('InboxIcon', InboxIcon);
    app.component('ChevronDoubleRightIcon', ChevronDoubleRightIcon);
    app.component('ChevronDoubleLeftIcon', ChevronDoubleLeftIcon);
    app.component('LogoutIcon', LogoutIcon);
    app.component('PowerIcon', PowerIcon);
    app.component('BulbIcon', BulbIcon);
    app.component('EditIcon', EditIcon);
    app.component('FolderIcon', FolderIcon);
    app.component('UsersIcon', UsersIcon);
  }
};
