version: '3.4'

services:
#  smartHub:
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
##     - ASPNETCORE_URLS=http://*:5000
##     - Use_StaticFiles=true
#      - Seed_Db=false
#      - Pgsql_User=postgres
#      - Pgsql_pwd=1234
#    ports:
#      - "5001"
#      - "5000"
#    volumes:
#      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  database:
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data